
# Available storage types:
# sql ( recommend )
# mysql ( for cross server storage )
# mongodb ( recommended too )
# yaml ( Recommended if u want to edit homes via your file manager )
storage: sql

mongo:
  uri: ""

mysql:
  host: "0.0.0.0"
  port: 3306
  username: "rhomes"
  password: "qwerty"
  database: "rhomes"