

bad-blocks:
  enabled: true
  radius: 3 # Scans for 3 blocks around the location
  blocks: # use 1.13+ material names
    - LAVA
    - TNT
    - CACTUS
    - FIRE
    - STRUCTURE_VOID
    - VOID_AIR