home-protection:
  enabled: true
  pvp:
    enabled: true # If true, players can pvp in homes, see below for details.
    pvp-inverted: true # If true, the homeowner can attack anyone who is in their home, while the other person can't, if false, both can't attack each other
  interaction-blocks: # The blocks ( chests, trapdoors, doors etc. ) you don't want the player to mess with.
    - CHEST
    - IRON_TRAPDOOR
    - ACACIA_TRAPDOOR # For some reason this is an oak trapdoor in 1.8 lol
    - OAK_DOOR
    - ACACIA_DOOR
    - BIRCH_DOOR
    - SUPRUCE_DOOR
    - DARK_OAK_DOOR

bad-blocks:
  enabled: true
  radius: 3 # Scans for 3 blocks around the location
  blocks: # use 1.13+ material names
    - LAVA
    - TNT
    - CACTUS
    - FIRE
    - STRUCTURE_VOID
    - VOID_AIR